<?php

namespace ContainerZXWP8Ra;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QACakKlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qACakKl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qACakKl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tragetRepository' => ['privates', 'App\\Repository\\TragetRepository', 'getTragetRepositoryService', true],
        ], [
            'tragetRepository' => 'App\\Repository\\TragetRepository',
        ]);
    }
}
