<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Traget extends \App\Entity\Traget implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id_traget', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'depart', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'arrivee', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'passager', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'date_depart', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'heure_depart', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'heure_arrivee', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'reservations'];
        }

        return ['__isInitialized__', 'id_traget', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'depart', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'arrivee', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'passager', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'date_depart', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'heure_depart', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'heure_arrivee', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Traget' . "\0" . 'reservations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Traget $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdTraget(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTraget', []);

        return parent::getIdTraget();
    }

    /**
     * {@inheritDoc}
     */
    public function getDepart(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepart', []);

        return parent::getDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepart(string $depart): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepart', [$depart]);

        return parent::setDepart($depart);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrivee(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrivee', []);

        return parent::getArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setArrivee(string $arrivee): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrivee', [$arrivee]);

        return parent::setArrivee($arrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassager(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassager', []);

        return parent::getPassager();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassager(string $passager): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassager', [$passager]);

        return parent::setPassager($passager);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDepart(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDepart', []);

        return parent::getDateDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDepart(\DateTimeInterface $date_depart): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDepart', [$date_depart]);

        return parent::setDateDepart($date_depart);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDepart(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDepart', []);

        return parent::getHeureDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDepart(\DateTimeInterface $heure_depart): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDepart', [$heure_depart]);

        return parent::setHeureDepart($heure_depart);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureArrivee(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureArrivee', []);

        return parent::getHeureArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureArrivee(\DateTimeInterface $heure_arrivee): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureArrivee', [$heure_arrivee]);

        return parent::setHeureArrivee($heure_arrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\App\Entity\Reservation $reservation): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', [$reservation]);

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\App\Entity\Reservation $reservation): \App\Entity\Traget
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', [$reservation]);

        return parent::removeReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
