<?php

namespace ContainerAkxxL4S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pe4_I_UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pe4.I.u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pe4.I.u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sec' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'sec' => '?',
        ]);
    }
}
