<?php

namespace ContainerAkxxL4S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SrCgMmiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SrCgMmi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SrCgMmi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'traget' => ['privates', '.errored..service_locator.SrCgMmi.App\\Entity\\Traget', NULL, 'Cannot autowire service ".service_locator.SrCgMmi": it references class "App\\Entity\\Traget" but no such service exists.'],
        ], [
            'traget' => 'App\\Entity\\Traget',
        ]);
    }
}
