<?php

namespace ContainerAkxxL4S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTragetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SrCgMmi.App\Entity\Traget' shared service.
     *
     * @return \App\Entity\Traget
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SrCgMmi": it references class "App\\Entity\\Traget" but no such service exists.');
    }
}
