<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAkxxL4S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAkxxL4S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAkxxL4S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAkxxL4S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAkxxL4S\App_KernelDevDebugContainer([
    'container.build_hash' => 'AkxxL4S',
    'container.build_id' => '39cf0859',
    'container.build_time' => 1621046633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAkxxL4S');
